version: '3.9'

services:
  face-registration:
    build:
      context: ./services/face-registration
      dockerfile: Dockerfile
    container_name: face-recognition-service
    ports:
      - '5001:5001'
    environment:
      - PYTHONUNBUFFERED=1
      - RAG_SERVICE_URL=http://rag-engine:5002
    volumes:
      - ./services/face-registration/data:/app/data
      - ./logs:/app/logs
    networks:
      - face-recognition-network
    restart: unless-stopped

  rag-engine:
    build:
      context: ./services/rag-engine
      dockerfile: Dockerfile
    container_name: rag-engine-service
    ports:
      - '5002:5002'
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./services/rag-engine/data:/app/data
      - ./logs:/app/logs
    networks:
      - face-recognition-network
    restart: unless-stopped

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - PORT=3001
      - FACE_SERVICE_URL=http://face-registration:5001
      - RAG_SERVICE_URL=http://rag-engine:5002
    volumes:
      - ./logs:/app/logs
    depends_on:
      - face-registration
      - rag-engine
    networks:
      - face-recognition-network
    restart: unless-stopped

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_WEBSOCKET_URL=ws://localhost:3001/ws
    depends_on:
      - backend
    networks:
      - face-recognition-network
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  face-recognition-network:
    driver: bridge

volumes:
  data:
  logs:
